/**
 * Screen Object generator (GTD-056).
 *
 * Walks a running game's tree via the driver API, collects every node
 * carrying test_id metadata, and renders a ready-to-import Screen Objects
 * module (docs/testing/03 §6.1). The generated code depends only on
 * @godriver/core.
 */

const MAX_DEPTH = 32;

/**
 * Walk the tree from /root and collect nodes with test_id metadata.
 *
 * @param {{ request: (path: string) => Promise<Record<string, unknown>> }} driver
 * @returns {Promise<Array<{ testId: string, path: string, type: string }>>}
 */
export async function generateScreens(driver) {
	/** @type {Array<{ testId: string, path: string, type: string }>} */
	const entries = [];
	/** @type {Array<{ path: string, depth: number }>} */
	const frontier = [{ path: "/root", depth: 0 }];
	const visited = new Set();

	while (frontier.length > 0) {
		const { path, depth } = /** @type {{ path: string, depth: number }} */ (frontier.pop());
		if (visited.has(path) || depth > MAX_DEPTH) {
			continue;
		}
		visited.add(path);
		const info = await driver.request(`/node${path}`);
		const testId = info.test_id;
		if (testId != null) {
			entries.push({ testId: String(testId), path: String(info.path), type: String(info.type) });
		}
		const children = /** @type {string[]} */ (info.children ?? []);
		for (const name of children) {
			frontier.push({ path: `${path}/${name}`, depth: depth + 1 });
		}
	}
	return entries;
}

/**
 * Render the Screen Objects module source for the collected entries.
 *
 * @param {Array<{ testId: string, path: string, type: string }>} entries
 * @param {{ godotVersion?: string }} [meta]
 * @returns {string} ES module source
 */
export function renderScreensModule(entries, meta = {}) {
	const stamp = new Date().toISOString();
	const version = meta.godotVersion ?? "unknown";
	const mapLines = entries
		.map((e) => `\t\t${JSON.stringify(e.testId)}: ${JSON.stringify(e.path)}, // ${e.type}`)
		.join("\n");
	return `// Generated by \`godriver generate\` (GTD-056) - do not edit by hand.
// Captured ${stamp} from Godot ${version}. Re-run the generator after scene changes.
// Runtime dependency: @godriver/core only.
import { connect } from "@godriver/core";

const SCREENS_TEST_IDS = ${JSON.stringify(mapFromEntries(entries), null, "\t")};

export const TEST_IDS = SCREENS_TEST_IDS;

/**
 * Screen Objects skeleton for the captured scene tree.
 * Generic helpers keyed by test_id; extend with game-specific flows.
 */
export class GameScreens {
	/**
	 * @param {import("@godriver/core").Driver} driver
	 */
	constructor(driver) {
		this.driver = driver;
		this.testIds = SCREENS_TEST_IDS;
	}

	/** @param {string} name test_id key */
	path(name) {
		const p = this.testIds[name];
		if (!p) {
			throw new Error(\`unknown test_id '\${name}' (available: \${Object.keys(this.testIds).join(", ")})\`);
		}
		return p;
	}

	/** @param {string} name test_id key */
	async click(name) {
		return this.driver.click(this.path(name), { testId: true });
	}

	/** @param {string} name test_id key @param {string} text */
	async type(name, text) {
		return this.driver.type(this.path(name), text);
	}

	/** @param {string} name test_id key @param {{ expected?: boolean }} [opts] */
	async expectVisible(name, opts = {}) {
		return this.driver.assertVisible(this.path(name), opts);
	}

	/**
	 * Read a property (GTD-013).
	 * @param {string} name test_id key @param {string} prop
	 */
	async property(name, prop) {
		const data = await this.driver.request(\`/node\${this.path(name)}/property/\${encodeURIComponent(prop)}\`);
		return data.value;
	}

	/**
	 * Write a property - game-state seeding (GTD-055).
	 * @param {string} name test_id key @param {string} prop @param {unknown} value
	 */
	async setProperty(name, prop, value) {
		return this.driver.setProperty(this.path(name), prop, value);
	}

	/**
	 * Wait for a signal on the node (GTD-031).
	 * @param {string} name test_id key @param {string} signal @param {number} [timeoutMs]
	 */
	async waitForSignal(name, signal, timeoutMs = 10000) {
		return this.driver.waitSignal(this.path(name), signal, { timeoutMs });
	}
}


/**
 * Connect and build the Screen Objects handle.
 * @param {number} port
 * @param {import("@godriver/core").ConnectOptions} [opts]
 */
export async function createScreens(port, opts) {
	const driver = await connect(port, opts);
	return new GameScreens(driver);
}
`;
}

/** @param {Array<{ testId: string, path: string, type: string }>} entries @returns {Record<string, string>} */
function mapFromEntries(entries) {
	/** @type {Record<string, string>} */
	const out = {};
	for (const e of entries) {
		out[e.testId] = e.path;
	}
	return out;
}

